export const CHATBOT_CREATE_REQUEST = "CHATBOT_CREATE_REQUEST";
export const CHATBOT_CREATE_SUCCESS = "CHATBOT_CREATE_SUCCESS";
export const CHATBOT_CREATE_FAILURE = "CHATBOT_CREATE_FAILURE";

export const FETCH_CHATBOT_BY_PROJECT_ID_REQUEST =
  "FETCH_CHATBOTBY_PROJECT_ID_REQUEST";
export const FETCH_CHATBOT_BY_PROJECT_ID_SUCCESS =
  "FETCH_CHATBOTBY_PROJECT_ID_SUCCESS";
export const FETCH_CHATBOT_BY_PROJECT_ID_FAILURE =
  "FETCH_CHATBOTBY_PROJECT_ID_FAILURE";
